apiVersion: apps/v1
kind: Deployment
metadata:
  name: caring-note-api
  namespace: caring-note-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caring-note-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: caring-note-api
    spec:
      containers:
        - name: caring-note-api
          image: bsh998/caring-note-api:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'staging'
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://postgresql.default.svc.cluster.local:5432/caring_note_staging'
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret-staging
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret-staging
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRINGDOC_SWAGGER_UI_PATH
              value: '/swagger-ui'
            - name: SPRINGDOC_SWAGGERUI_URL
              value: '/v1/api-docs'
            - name: SPRINGDOC_API-DOCS_PATH
              value: '/v1/api-docs'
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: '/api/'
            - name: SPRING_JPA_HIBERNATE_DIALECT
              value: 'org.hibernate.dialect.PostgreSQLDialect'
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: 'org.postgresql.Driver'
            - name: SPRING_AI_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret-staging
                  key: OPEN_AI_API_KEY
            - name: NAVER_CLOVA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret-staging
                  key: CLOVA_API_KEY

          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: caring-note-api
spec:
  selector:
    app: caring-note-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
