apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caringnote-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - caringnote.co.kr
    secretName: caringnote-tls
  rules:
  - host: caringnote.co.kr
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: caring-note-api
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: caring-note-web
            port:
              number: 80
