config:
  clientID: your-client-id
  clientSecret: your-client-secret
  provider: keycloak
  redirectURL: https://caringnote.com/oauth2/callback
  oidcIssuerURL: https://keycloak.caringnote.co.kr/auth/realms/caringnote
extraArgs:
  scope: "openid email profile"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  hosts:
    - caringnote.co.kr
  tls:
    - secretName: caringnote-tls
      hosts:
        - caringnote.co.kr
