config:
  clientID: caringnote
  clientSecret: C1durQrc4nSq38wwr8uDQokwepWqDQGr
  provider: keycloak
  redirectURL: https://caringnote.com/keycloak/oauth2/callback
  oidcIssuerURL: https://keycloak.caringnote.co.kr/keycloak/auth/realms/caringnote
extraArgs:
  scope: "openid email profile"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  hosts:
    - caringnote.co.kr
  tls:
    - secretName: caringnote-tls
      hosts:
        - caringnote.co.kr
